# Exercise 11: Frequent Pattern Mining of PM2.5 Sensor Data

Student ID: s1320190  
Name: Mutsuki Notoya

## GitHub Repository

[PAMI Forked Repository](https://github.com/s1320190/PAMI)

In [1]:
%pip install -U pami plotly pandas numpy

Collecting pami
  Downloading pami-2026.7.24.1-py3-none-any.whl.metadata (80 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.2/80.2 kB 2.1 MB/s eta 0:00:00
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Collecting plotly
  Downloading plotly-6.9.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting pandas
  Downloading pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 7.0 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Collecting numpy
  Downloading numpy-2.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from pami) (5.9.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from pami) (3.10.0)
Collecting resource (from pami)
  Downloading Resource-0.2.1-py2.py3-none-any.whl.metadata (478 bytes)
Collecting validators (from pami)
  Downloading validators-0.35.0-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from pami) (2.5.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from pami) (11.3.0)
Requirement already satisfied: sphinx in /usr/local/lib/python3.12/dist-packages (from pami) (8.2.3)
Collecting sphinx-rtd-theme (from pami)
  Downloading sphinx_rtd_theme-3.1.0-py2.py3-none-any.whl.metadata (4.5 kB)
Collecting discord.py (from pami)
  Downloading discord_py-2.7.1-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from pami) (3.6.1)
Collecting deprecated (from pami)
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting fastparquet (from pami)
  Downloading fastparquet-2026.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: narwhals>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from plotly) (2.24.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: wrapt<3,>=1.10 in /usr/local/lib/python3.12/dist-packages (from deprecated->pami) (2.2.2)
Requirement already satisfied: aiohttp<4,>=3.7.4 in /usr/local/lib/python3.12/dist-packages (from discord.py->pami) (3.14.1)
Requirement already satisfied: cramjam>=2.3 in /usr/local/lib/python3.12/dist-packages (from fastparquet->pami) (2.11.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from fastparquet->pami) (2025.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pami) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pami) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pami) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pami) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pami) (3.3.2)
Collecting JsonForm>=0.0.2 (from resource->pami)
  Downloading JsonForm-0.0.2.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... done
Collecting JsonSir>=0.0.2 (from resource->pami)
  Downloading JsonSir-0.0.2.tar.gz (2.2 kB)
  Preparing metadata (setup.py) ... done
Collecting python-easyconfig>=0.1.0 (from resource->pami)
  Downloading Python_EasyConfig-0.1.7-py2.py3-none-any.whl.metadata (462 bytes)
Requirement already satisfied: sphinxcontrib-applehelp>=1.0.7 in /usr/local/lib/python3.12/dist-packages (from sphinx->pami) (2.0.0)
Requirement already satisfied: sphinxcontrib-devhelp>=1.0.6 in /usr/local/lib/python3.12/dist-packages (from sphinx->pami) (2.0.0)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from sphinx->pami) (2.1.0)
Requirement already satisfied: sphinxcontrib-jsmath>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from sphinx->pami) (1.0.1)
Requirement already satisfied: sphinxcontrib-qthelp>=1.0.6 in /usr/local/lib/python3.12/dist-packages (from sphinx->pami) (2.0.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in /usr/local/lib/python3.12/dist-packages (from sphinx->pami) (2.0.0)
Requirement already satisfied: Jinja2>=3.1 in /usr/local/lib/python3.12/dist-packages (from sphinx->pami) (3.1.6)
Requirement already satisfied: Pygments>=2.17 in /usr/local/lib/python3.12/dist-packages (from sphinx->pami) (2.20.0)
Requirement already satisfied: docutils<0.22,>=0.20 in /usr/local/lib/python3.12/dist-packages (from sphinx->pami) (0.21.2)
Requirement already satisfied: snowballstemmer>=2.2 in /usr/local/lib/python3.12/dist-packages (from sphinx->pami) (3.1.1)
Requirement already satisfied: babel>=2.13 in /usr/local/lib/python3.12/dist-packages (from sphinx->pami) (2.18.0)
Requirement already satisfied: alabaster>=0.7.14 in /usr/local/lib/python3.12/dist-packages (from sphinx->pami) (1.0.0)
Requirement already satisfied: imagesize>=1.3 in /usr/local/lib/python3.12/dist-packages (from sphinx->pami) (2.0.0)
Requirement already satisfied: requests>=2.30.0 in /usr/local/lib/python3.12/dist-packages (from sphinx->pami) (2.32.4)
Requirement already satisfied: roman-numerals-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sphinx->pami) (4.1.0)
Collecting sphinxcontrib-jquery<5,>=4 (from sphinx-rtd-theme->pami)
  Downloading sphinxcontrib_jquery-4.1-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.4->discord.py->pami) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.4->discord.py->pami) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.4->discord.py->pami) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.4->discord.py->pami) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.4->discord.py->pami) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.4->discord.py->pami) (0.5.2)
Requirement already satisfied: typing_extensions>=4.4 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.4->discord.py->pami) (4.16.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.4->discord.py->pami) (1.24.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from Jinja2>=3.1->sphinx->pami) (3.0.3)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.12/dist-packages (from JsonForm>=0.0.2->resource->pami) (4.26.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from python-easyconfig>=0.1.0->resource->pami) (6.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->sphinx->pami) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->sphinx->pami) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->sphinx->pami) (2026.6.17)
Requirement already satisfied: roman-numerals==4.1.0 in /usr/local/lib/python3.12/dist-packages (from roman-numerals-py>=1.0.0->sphinx->pami) (4.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema->JsonForm>=0.0.2->resource->pami) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema->JsonForm>=0.0.2->resource->pami) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema->JsonForm>=0.0.2->resource->pami) (2026.6.3)
Downloading pami-2026.7.24.1-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 61.1 MB/s eta 0:00:00
Downloading plotly-6.9.0-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 55.5 MB/s eta 0:00:00
Downloading pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 108.0 MB/s eta 0:00:00
Downloading numpy-2.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 88.9 MB/s eta 0:00:00
Downloading deprecated-1.3.1-py2.py3-none-any.whl (11 kB)
Downloading discord_py-2.7.1-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 31.5 MB/s eta 0:00:00
Downloading fastparquet-2026.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 88.2 MB/s eta 0:00:00
Downloading Resource-0.2.1-py2.py3-none-any.whl (25 kB)
Downloading sphinx_rtd_theme-3.1.0-py2.py3-none-any.whl (7.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 80.3 MB/s eta 0:00:00
Downloading validators-0.35.0-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.7/44.7 kB 4.0 MB/s eta 0:00:00
Downloading Python_EasyConfig-0.1.7-py2.py3-none-any.whl (5.4 kB)
Downloading sphinxcontrib_jquery-4.1-py2.py3-none-any.whl (121 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.1/121.1 kB 12.8 MB/s eta 0:00:00
Building wheels for collected packages: JsonForm, JsonSir
  Building wheel for JsonForm (setup.py) ... done
  Created wheel for JsonForm: filename=JsonForm-0.0.2-py3-none-any.whl size=3311 sha256=bbd593fc86c18e897cad740ee69efae8a59494b684eee3251e3763659025e39f
  Stored in directory: /root/.cache/pip/wheels/0b/29/3c/f5b5085becdbee0b282b60cda0028607f67adf8f099316a4a7
  Building wheel for JsonSir (setup.py) ... done
  Created wheel for JsonSir: filename=JsonSir-0.0.2-py3-none-any.whl size=4754 sha256=7b4afb46045395ed21547fd195deed0c20bbd4fb246a8af008068d0a5245831b
  Stored in directory: /root/.cache/pip/wheels/a8/ca/73/b3f5177e372c0c5057c77971c17b0b45f84381d0224b908e0a
Successfully built JsonForm JsonSir
Installing collected packages: JsonSir, validators, python-easyconfig, plotly, numpy, deprecated, pandas, sphinxcontrib-jquery, fastparquet, discord.py, sphinx-rtd-theme, JsonForm, resource, pami
  Attempting uninstall: plotly
    Found existing installation: plotly 5.24.1
    Uninstalling plotly-5.24.1:
      Successfully uninstalled plotly-5.24.1
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.5.1 which is incompatible.
Successfully installed JsonForm-0.0.2 JsonSir-0.0.2 deprecated-1.3.1 discord.py-2.7.1 fastparquet-2026.5.0 numpy-2.5.1 pami-2026.7.24.1 pandas-3.0.5 plotly-6.9.0 python-easyconfig-0.1.7 resource-0.2.1 sphinx-rtd-theme-3.1.0 sphinxcontrib-jquery-4.1 validators-0.35.0

In [1]:
%pip install -U PAMI plotly

Requirement already satisfied: PAMI in /usr/local/lib/python3.12/dist-packages (2026.7.24.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (6.9.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from PAMI) (5.9.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from PAMI) (3.0.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from PAMI) (3.10.0)
Requirement already satisfied: resource in /usr/local/lib/python3.12/dist-packages (from PAMI) (0.2.1)
Requirement already satisfied: validators in /usr/local/lib/python3.12/dist-packages (from PAMI) (0.35.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from PAMI) (2.5.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from PAMI) (11.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from PAMI) (2.5.1)
Requirement already satisfied: sphinx in /usr/local/lib/python3.12/dist-packages (from PAMI) (8.2.3)
Requirement already satisfied: sphinx-rtd-theme in /usr/local/lib/python3.12/dist-packages (from PAMI) (3.1.0)
Requirement already satisfied: discord.py in /usr/local/lib/python3.12/dist-packages (from PAMI) (2.7.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from PAMI) (3.6.1)
Requirement already satisfied: deprecated in /usr/local/lib/python3.12/dist-packages (from PAMI) (1.3.1)
Requirement already satisfied: fastparquet in /usr/local/lib/python3.12/dist-packages (from PAMI) (2026.5.0)
Requirement already satisfied: narwhals>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from plotly) (2.24.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.2)
Requirement already satisfied: wrapt<3,>=1.10 in /usr/local/lib/python3.12/dist-packages (from deprecated->PAMI) (2.2.2)
Requirement already satisfied: aiohttp<4,>=3.7.4 in /usr/local/lib/python3.12/dist-packages (from discord.py->PAMI) (3.14.1)
Requirement already satisfied: cramjam>=2.3 in /usr/local/lib/python3.12/dist-packages (from fastparquet->PAMI) (2.11.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from fastparquet->PAMI) (2025.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->PAMI) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->PAMI) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->PAMI) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->PAMI) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->PAMI) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->PAMI) (3.3.2)
Requirement already satisfied: JsonForm>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from resource->PAMI) (0.0.2)
Requirement already satisfied: JsonSir>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from resource->PAMI) (0.0.2)
Requirement already satisfied: python-easyconfig>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from resource->PAMI) (0.1.7)
Requirement already satisfied: sphinxcontrib-applehelp>=1.0.7 in /usr/local/lib/python3.12/dist-packages (from sphinx->PAMI) (2.0.0)
Requirement already satisfied: sphinxcontrib-devhelp>=1.0.6 in /usr/local/lib/python3.12/dist-packages (from sphinx->PAMI) (2.0.0)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from sphinx->PAMI) (2.1.0)
Requirement already satisfied: sphinxcontrib-jsmath>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from sphinx->PAMI) (1.0.1)
Requirement already satisfied: sphinxcontrib-qthelp>=1.0.6 in /usr/local/lib/python3.12/dist-packages (from sphinx->PAMI) (2.0.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in /usr/local/lib/python3.12/dist-packages (from sphinx->PAMI) (2.0.0)
Requirement already satisfied: Jinja2>=3.1 in /usr/local/lib/python3.12/dist-packages (from sphinx->PAMI) (3.1.6)
Requirement already satisfied: Pygments>=2.17 in /usr/local/lib/python3.12/dist-packages (from sphinx->PAMI) (2.20.0)
Requirement already satisfied: docutils<0.22,>=0.20 in /usr/local/lib/python3.12/dist-packages (from sphinx->PAMI) (0.21.2)
Requirement already satisfied: snowballstemmer>=2.2 in /usr/local/lib/python3.12/dist-packages (from sphinx->PAMI) (3.1.1)
Requirement already satisfied: babel>=2.13 in /usr/local/lib/python3.12/dist-packages (from sphinx->PAMI) (2.18.0)
Requirement already satisfied: alabaster>=0.7.14 in /usr/local/lib/python3.12/dist-packages (from sphinx->PAMI) (1.0.0)
Requirement already satisfied: imagesize>=1.3 in /usr/local/lib/python3.12/dist-packages (from sphinx->PAMI) (2.0.0)
Requirement already satisfied: requests>=2.30.0 in /usr/local/lib/python3.12/dist-packages (from sphinx->PAMI) (2.32.4)
Requirement already satisfied: roman-numerals-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sphinx->PAMI) (4.1.0)
Requirement already satisfied: sphinxcontrib-jquery<5,>=4 in /usr/local/lib/python3.12/dist-packages (from sphinx-rtd-theme->PAMI) (4.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.4->discord.py->PAMI) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.4->discord.py->PAMI) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.4->discord.py->PAMI) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.4->discord.py->PAMI) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.4->discord.py->PAMI) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.4->discord.py->PAMI) (0.5.2)
Requirement already satisfied: typing_extensions>=4.4 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.4->discord.py->PAMI) (4.16.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.4->discord.py->PAMI) (1.24.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from Jinja2>=3.1->sphinx->PAMI) (3.0.3)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.12/dist-packages (from JsonForm>=0.0.2->resource->PAMI) (4.26.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->PAMI) (1.17.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from python-easyconfig>=0.1.0->resource->PAMI) (6.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->sphinx->PAMI) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->sphinx->PAMI) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->sphinx->PAMI) (2026.6.17)
Requirement already satisfied: roman-numerals==4.1.0 in /usr/local/lib/python3.12/dist-packages (from roman-numerals-py>=1.0.0->sphinx->PAMI) (4.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema->JsonForm>=0.0.2->resource->PAMI) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema->JsonForm>=0.0.2->resource->PAMI) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema->JsonForm>=0.0.2->resource->PAMI) (2026.6.3)

In [2]:
%pip install pandas==2.2.2 "numpy<2.1"

Collecting pandas==2.2.2
  Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting numpy<2.1
  Downloading numpy-2.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 5.9 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.17.0)
Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 56.4 MB/s eta 0:00:00
Downloading numpy-2.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.2/19.2 MB 69.4 MB/s eta 0:00:00
Installing collected packages: numpy, pandas
  Attempting uninstall: numpy
    Found existing installation: numpy 2.5.1
    Uninstalling numpy-2.5.1:
      Successfully uninstalled numpy-2.5.1
  Attempting uninstall: pandas
    Found existing installation: pandas 3.0.5
    Uninstalling pandas-3.0.5:
      Successfully uninstalled pandas-3.0.5
Successfully installed numpy-2.0.2 pandas-2.2.2

In [1]:
import numpy as np
import pandas as pd
import plotly
import PAMI

print("NumPy:", np.__version__)
print("pandas:", pd.__version__)
print("Plotly:", plotly.__version__)
print("PAMI imported successfully")

NumPy: 2.0.2
pandas: 2.2.2
Plotly: 6.9.0
PAMI imported successfully

In [2]:
from google.colab import files

print("演習10で作成したCSVファイルを選択してください。")

uploaded = files.upload()

if not uploaded:
    raise RuntimeError("ファイルがアップロードされませんでした。")

data_file = next(iter(uploaded.keys()))

print("アップロードしたファイル:", data_file)

演習10で作成したCSVファイルを選択してください。

Saving airPollutionDataFrame.csv to airPollutionDataFrame.csv
アップロードしたファイル: airPollutionDataFrame.csv

In [3]:
import pandas as pd

def read_csv_with_encoding(file_name):
    encodings = ["utf-8", "utf-8-sig", "cp932", "shift_jis"]

    for encoding in encodings:
        try:
            df = pd.read_csv(file_name, encoding=encoding)
            print("使用した文字コード:", encoding)
            return df
        except UnicodeDecodeError:
            continue

    raise RuntimeError("CSVファイルを読み込めませんでした。")

original_df = read_csv_with_encoding(data_file)

print("データの行数と列数:", original_df.shape)
display(original_df.head())

使用した文字コード: utf-8
データの行数と列数: (118, 1628)

,Timestamp,Point(01101010),Point(01101020),Point(01101520),Point(01101540),Point(01102010),Point(01102020),Point(01102510),Point(01103520),Point(01104030),...,Point(47201580),Point(47206020),Point(47207020),Point(47208510),Point(47209080),Point(47210060),Point(47211050),Point(47301950),Point(47322010),Point(47329010)
0,2026-07-01 01:00:00,NaN,NaN,6.0,5.0,5.0,6.0,6.0,NaN,NaN,...,NaN,4.0,NaN,NaN,3.0,NaN,4.0,6.0,NaN,NaN
1,2026-07-01 02:00:00,NaN,NaN,7.0,4.0,11.0,0.0,6.0,NaN,NaN,...,NaN,3.0,NaN,NaN,5.0,NaN,4.0,4.0,NaN,NaN
2,2026-07-01 03:00:00,NaN,NaN,9.0,5.0,14.0,5.0,9.0,NaN,NaN,...,NaN,3.0,NaN,NaN,4.0,NaN,4.0,3.0,NaN,NaN
3,2026-07-01 04:00:00,NaN,NaN,10.0,7.0,14.0,4.0,13.0,NaN,NaN,...,NaN,4.0,NaN,NaN,4.0,NaN,4.0,3.0,NaN,NaN
4,2026-07-01 05:00:00,NaN,NaN,14.0,12.0,11.0,15.0,16.0,NaN,NaN,...,NaN,4.0,NaN,NaN,4.0,NaN,4.0,4.0,NaN,NaN

In [4]:
# NaNを0に置き換える
processed_df = original_df.copy()

processed_df = processed_df.fillna(0)

print("残っているNaN数:", processed_df.isna().sum().sum())

display(processed_df.head())

残っているNaN数: 0

,Timestamp,Point(01101010),Point(01101020),Point(01101520),Point(01101540),Point(01102010),Point(01102020),Point(01102510),Point(01103520),Point(01104030),...,Point(47201580),Point(47206020),Point(47207020),Point(47208510),Point(47209080),Point(47210060),Point(47211050),Point(47301950),Point(47322010),Point(47329010)
0,2026-07-01 01:00:00,0.0,0.0,6.0,5.0,5.0,6.0,6.0,0.0,0.0,...,0.0,4.0,0.0,0.0,3.0,0.0,4.0,6.0,0.0,0.0
1,2026-07-01 02:00:00,0.0,0.0,7.0,4.0,11.0,0.0,6.0,0.0,0.0,...,0.0,3.0,0.0,0.0,5.0,0.0,4.0,4.0,0.0,0.0
2,2026-07-01 03:00:00,0.0,0.0,9.0,5.0,14.0,5.0,9.0,0.0,0.0,...,0.0,3.0,0.0,0.0,4.0,0.0,4.0,3.0,0.0,0.0
3,2026-07-01 04:00:00,0.0,0.0,10.0,7.0,14.0,4.0,13.0,0.0,0.0,...,0.0,4.0,0.0,0.0,4.0,0.0,4.0,3.0,0.0,0.0
4,2026-07-01 05:00:00,0.0,0.0,14.0,12.0,11.0,15.0,16.0,0.0,0.0,...,0.0,4.0,0.0,0.0,4.0,0.0,4.0,4.0,0.0,0.0

In [5]:
# Timestamp列以外を取得
sensor_columns = [
    c for c in processed_df.columns
    if c.lower() != "timestamp"
]

# 数値型へ変換
for c in sensor_columns:
    processed_df[c] = pd.to_numeric(
        processed_df[c],
        errors="coerce"
    ).fillna(0)

# 100以上を0に置換
processed_df[sensor_columns] = processed_df[sensor_columns].mask(
    processed_df[sensor_columns] >= 100,
    0
)

print("最大値:", processed_df[sensor_columns].max().max())

display(processed_df.head())

最大値: 99.0

,Timestamp,Point(01101010),Point(01101020),Point(01101520),Point(01101540),Point(01102010),Point(01102020),Point(01102510),Point(01103520),Point(01104030),...,Point(47201580),Point(47206020),Point(47207020),Point(47208510),Point(47209080),Point(47210060),Point(47211050),Point(47301950),Point(47322010),Point(47329010)
0,2026-07-01 01:00:00,0.0,0.0,6.0,5.0,5.0,6.0,6.0,0.0,0.0,...,0.0,4.0,0.0,0.0,3.0,0.0,4.0,6.0,0.0,0.0
1,2026-07-01 02:00:00,0.0,0.0,7.0,4.0,11.0,0.0,6.0,0.0,0.0,...,0.0,3.0,0.0,0.0,5.0,0.0,4.0,4.0,0.0,0.0
2,2026-07-01 03:00:00,0.0,0.0,9.0,5.0,14.0,5.0,9.0,0.0,0.0,...,0.0,3.0,0.0,0.0,4.0,0.0,4.0,3.0,0.0,0.0
3,2026-07-01 04:00:00,0.0,0.0,10.0,7.0,14.0,4.0,13.0,0.0,0.0,...,0.0,4.0,0.0,0.0,4.0,0.0,4.0,3.0,0.0,0.0
4,2026-07-01 05:00:00,0.0,0.0,14.0,12.0,11.0,15.0,16.0,0.0,0.0,...,0.0,4.0,0.0,0.0,4.0,0.0,4.0,4.0,0.0,0.0

In [6]:
# Timestamp列を削除

if "Timestamp" in processed_df.columns:
    sensor_df = processed_df.drop(columns=["Timestamp"])
elif "timestamp" in processed_df.columns:
    sensor_df = processed_df.drop(columns=["timestamp"])
else:
    raise Exception("Timestamp column not found.")

print("データサイズ:", sensor_df.shape)

display(sensor_df.head())

データサイズ: (118, 1627)

,Point(01101010),Point(01101020),Point(01101520),Point(01101540),Point(01102010),Point(01102020),Point(01102510),Point(01103520),Point(01104030),Point(01105520),...,Point(47201580),Point(47206020),Point(47207020),Point(47208510),Point(47209080),Point(47210060),Point(47211050),Point(47301950),Point(47322010),Point(47329010)
0,0.0,0.0,6.0,5.0,5.0,6.0,6.0,0.0,0.0,7.0,...,0.0,4.0,0.0,0.0,3.0,0.0,4.0,6.0,0.0,0.0
1,0.0,0.0,7.0,4.0,11.0,0.0,6.0,0.0,0.0,6.0,...,0.0,3.0,0.0,0.0,5.0,0.0,4.0,4.0,0.0,0.0
2,0.0,0.0,9.0,5.0,14.0,5.0,9.0,0.0,0.0,6.0,...,0.0,3.0,0.0,0.0,4.0,0.0,4.0,3.0,0.0,0.0
3,0.0,0.0,10.0,7.0,14.0,4.0,13.0,0.0,0.0,9.0,...,0.0,4.0,0.0,0.0,4.0,0.0,4.0,3.0,0.0,0.0
4,0.0,0.0,14.0,12.0,11.0,15.0,16.0,0.0,0.0,14.0,...,0.0,4.0,0.0,0.0,4.0,0.0,4.0,4.0,0.0,0.0

In [7]:
THRESHOLD = 15

transactions = []

for _, row in sensor_df.iterrows():

    transaction = []

    for column in sensor_df.columns:

        if row[column] >= THRESHOLD:
            transaction.append(column)

    transactions.append(transaction)

print("Transaction数:", len(transactions))

print("最初の5件")
for t in transactions[:5]:
    print(t)

Transaction数: 118
最初の5件
['Point(04104010)', 'Point(04206010)', 'Point(04341010)', 'Point(06206010)', 'Point(07201200)', 'Point(08203010)', 'Point(11209010)', 'Point(13201020)', 'Point(13201040)', 'Point(13205010)', 'Point(13218010)', 'Point(13303520)', 'Point(14209050)', 'Point(14212530)', 'Point(14401010)', 'Point(18201040)', 'Point(18201540)', 'Point(18202020)', 'Point(18205010)', 'Point(18361010)', 'Point(18381010)', 'Point(18441010)', 'Point(19201030)', 'Point(19202030)', 'Point(19205020)', 'Point(19206010)', 'Point(19321030)', 'Point(19441030)', 'Point(20205010)', 'Point(20421030)', 'Point(21201030)', 'Point(21204020)', 'Point(21205360)', 'Point(21209020)', 'Point(21210501)', 'Point(21211010)', 'Point(21212510)', 'Point(21214510)', 'Point(21215950)', 'Point(21218010)', 'Point(21221010)', 'Point(21401010)', 'Point(22211010)', 'Point(22327010)', 'Point(22382010)', 'Point(23112060)', 'Point(23211020)', 'Point(23211040)', 'Point(23211060)', 'Point(23216110)', 'Point(23218010)', 'Point(23220510)', 'Point(23226010)', 'Point(24201020)', 'Point(24201030)', 'Point(24202030)', 'Point(24202050)', 'Point(24202060)', 'Point(24202510)', 'Point(24203010)', 'Point(24204010)', 'Point(24205510)', 'Point(24206020)', 'Point(24206030)', 'Point(24207020)', 'Point(24207510)', 'Point(24208010)', 'Point(24210010)', 'Point(24213010)', 'Point(24215010)', 'Point(24323010)', 'Point(24442010)', 'Point(25201080)', 'Point(25201510)', 'Point(25201540)', 'Point(25202090)', 'Point(25203030)', 'Point(25204050)', 'Point(25205030)', 'Point(25206030)', 'Point(25206510)', 'Point(25207010)', 'Point(25209010)', 'Point(25212010)', 'Point(26102510)', 'Point(26104010)', 'Point(26104060)', 'Point(26104510)', 'Point(26104520)', 'Point(26107510)', 'Point(26109010)', 'Point(26109030)', 'Point(26110010)', 'Point(26110510)', 'Point(26111010)', 'Point(26201040)', 'Point(26204010)', 'Point(26206010)', 'Point(26207030)', 'Point(26208020)', 'Point(26210510)', 'Point(26213010)', 'Point(26303510)', 'Point(26322020)', 'Point(26342020)', 'Point(26343010)', 'Point(26362020)', 'Point(26366030)', 'Point(26367010)', 'Point(27104010)', 'Point(27104030)', 'Point(27108010)', 'Point(27113510)', 'Point(27117510)', 'Point(27118020)', 'Point(27120510)', 'Point(27125030)', 'Point(27125510)', 'Point(27143510)', 'Point(27146010)', 'Point(27201030)', 'Point(27201080)', 'Point(27201090)', 'Point(27201340)', 'Point(27201600)', 'Point(27202060)', 'Point(27203080)', 'Point(27204030)', 'Point(27205080)', 'Point(27205530)', 'Point(27206030)', 'Point(27207020)', 'Point(27207030)', 'Point(27207510)', 'Point(27208010)', 'Point(27209510)', 'Point(27212010)', 'Point(27213050)', 'Point(27214020)', 'Point(27215010)', 'Point(27216010)', 'Point(27216520)', 'Point(27217510)', 'Point(27218010)', 'Point(27219040)', 'Point(27221010)', 'Point(27225010)', 'Point(27225510)', 'Point(27227030)', 'Point(27227040)', 'Point(27301010)', 'Point(27321010)', 'Point(28101010)', 'Point(28101030)', 'Point(28101520)', 'Point(28102010)', 'Point(28102040)', 'Point(28107010)', 'Point(28107020)', 'Point(28108010)', 'Point(28108020)', 'Point(28108510)', 'Point(28109520)', 'Point(28111510)', 'Point(28201020)', 'Point(28201040)', 'Point(28201050)', 'Point(28201060)', 'Point(28201070)', 'Point(28201520)', 'Point(28201530)', 'Point(28202020)', 'Point(28202520)', 'Point(28202540)', 'Point(28202580)', 'Point(28203020)', 'Point(28203060)', 'Point(28203510)', 'Point(28204570)', 'Point(28205010)', 'Point(28206090)', 'Point(28206510)', 'Point(28208010)', 'Point(28208510)', 'Point(28210010)', 'Point(28210030)', 'Point(28210180)', 'Point(28210520)', 'Point(28211010)', 'Point(28212010)', 'Point(28213010)', 'Point(28214010)', 'Point(28214510)', 'Point(28216010)', 'Point(28216520)', 'Point(28217010)', 'Point(28217520)', 'Point(28218510)', 'Point(28219010)', 'Point(28381010)', 'Point(28382010)', 'Point(28464010)', 'Point(29201020)', 'Point(29202010)', 'Point(29204010)', 'Point(29206010)', 'Point(29208010)', 'Point(29209010)', 'Point(29363010)', 'Point(29425010)', 'Point(30201020)', 'Point(30201080)', 'Point(30201110)', 'Point(30201130)', 'Point(30201270)', 'Point(30202140)', 'Point(30203010)', 'Point(30322010)', 'Point(32204040)', 'Point(33201040)', 'Point(33201060)', 'Point(33201120)', 'Point(33201130)', 'Point(33201160)', 'Point(33201190)', 'Point(33201210)', 'Point(33202060)', 'Point(33202090)', 'Point(33202110)', 'Point(33202140)', 'Point(33202170)', 'Point(33202180)', 'Point(33202400)', 'Point(33202420)', 'Point(33202530)', 'Point(33203020)', 'Point(33204040)', 'Point(33205020)', 'Point(33208010)', 'Point(33209010)', 'Point(33210010)', 'Point(33211060)', 'Point(33423010)', 'Point(33423510)', 'Point(33503010)', 'Point(33681010)', 'Point(34102020)', 'Point(34104510)', 'Point(34105010)', 'Point(34105020)', 'Point(34105510)', 'Point(34201010)', 'Point(34201020)', 'Point(34201250)', 'Point(34201260)', 'Point(34201510)', 'Point(34201520)', 'Point(34202010)', 'Point(34202040)', 'Point(34203010)', 'Point(34204520)', 'Point(34207040)', 'Point(34207060)', 'Point(34207090)', 'Point(34207310)', 'Point(34207320)', 'Point(34207510)', 'Point(34209020)', 'Point(34211200)', 'Point(34212030)', 'Point(34369010)', 'Point(35201020)', 'Point(35201030)', 'Point(35201040)', 'Point(35201250)', 'Point(35202020)', 'Point(35202360)', 'Point(35203010)', 'Point(35204010)', 'Point(35205010)', 'Point(35206010)', 'Point(35207090)', 'Point(35208010)', 'Point(35208030)', 'Point(35209010)', 'Point(35212010)', 'Point(35213010)', 'Point(35214020)', 'Point(35321010)', 'Point(36202010)', 'Point(36205010)', 'Point(36342010)', 'Point(36361010)', 'Point(36402010)', 'Point(36461010)', 'Point(36483010)', 'Point(37201010)', 'Point(37201080)', 'Point(37201090)', 'Point(37201100)', 'Point(37201550)', 'Point(37202010)', 'Point(37203010)', 'Point(37204010)', 'Point(37205010)', 'Point(37206010)', 'Point(37322010)', 'Point(37386010)', 'Point(38201020)', 'Point(38201030)', 'Point(38201080)', 'Point(38201090)', 'Point(38201530)', 'Point(38202100)', 'Point(38203010)', 'Point(38204010)', 'Point(38205010)', 'Point(38205060)', 'Point(38206050)', 'Point(38208030)', 'Point(38209050)', 'Point(38212040)', 'Point(38380010)', 'Point(38401010)', 'Point(38421010)', 'Point(39201350)', 'Point(39203010)', 'Point(39206020)', 'Point(39210010)', 'Point(39212010)', 'Point(39381030)', 'Point(39405950)', 'Point(40101020)', 'Point(40101510)', 'Point(40103010)', 'Point(40103120)', 'Point(40103130)', 'Point(40105010)', 'Point(40106010)', 'Point(40107040)', 'Point(40108510)', 'Point(40109010)', 'Point(40131030)', 'Point(40135060)', 'Point(40135530)', 'Point(40214010)', 'Point(40223510)', 'Point(44201350)', 'Point(44201370)', 'Point(44202020)', 'Point(44203070)', 'Point(44213010)', 'Point(44341030)', 'Point(44381010)', 'Point(45401010)']
['Point(04206010)', 'Point(06208010)', 'Point(11209010)', 'Point(13201020)', 'Point(13201040)', 'Point(13201510)', 'Point(13205010)', 'Point(13218010)', 'Point(13303520)', 'Point(14209010)', 'Point(14209530)', 'Point(14212520)', 'Point(14214020)', 'Point(14401010)', 'Point(18201040)', 'Point(18201540)', 'Point(18202020)', 'Point(18381010)', 'Point(18441010)', 'Point(19201030)', 'Point(19202030)', 'Point(19206010)', 'Point(19321030)', 'Point(19441030)', 'Point(20205010)', 'Point(20421030)', 'Point(21201010)', 'Point(21201030)', 'Point(21203010)', 'Point(21204020)', 'Point(21205360)', 'Point(21209020)', 'Point(21210501)', 'Point(21211010)', 'Point(21212510)', 'Point(21214510)', 'Point(21215950)', 'Point(21218010)', 'Point(21220010)', 'Point(21221010)', 'Point(21401010)', 'Point(22211010)', 'Point(22215010)', 'Point(22221010)', 'Point(22327010)', 'Point(22382010)', 'Point(23110040)', 'Point(23112510)', 'Point(23202560)', 'Point(23211020)', 'Point(23211040)', 'Point(23211060)', 'Point(23211530)', 'Point(23216110)', 'Point(23218010)', 'Point(23220510)', 'Point(23226010)', 'Point(24201020)', 'Point(24201030)', 'Point(24202030)', 'Point(24202050)', 'Point(24202060)', 'Point(24202510)', 'Point(24202530)', 'Point(24203010)', 'Point(24204010)', 'Point(24205510)', 'Point(24206020)', 'Point(24206030)', 'Point(24207020)', 'Point(24207510)', 'Point(24208010)', 'Point(24210010)', 'Point(24212010)', 'Point(24213010)', 'Point(24323010)', 'Point(24344020)', 'Point(24442010)', 'Point(25201080)', 'Point(25201510)', 'Point(25202090)', 'Point(25203030)', 'Point(25204050)', 'Point(25205030)', 'Point(25206030)', 'Point(25206510)', 'Point(25207010)', 'Point(25209010)', 'Point(25212010)', 'Point(26102510)', 'Point(26104010)', 'Point(26104060)', 'Point(26104510)', 'Point(26104520)', 'Point(26107510)', 'Point(26109010)', 'Point(26109030)', 'Point(26110010)', 'Point(26110510)', 'Point(26111010)', 'Point(26204010)', 'Point(26206010)', 'Point(26207030)', 'Point(26208020)', 'Point(26210510)', 'Point(26213010)', 'Point(26303510)', 'Point(26322020)', 'Point(26342020)', 'Point(26343010)', 'Point(26362020)', 'Point(26366030)', 'Point(27104010)', 'Point(27106010)', 'Point(27108010)', 'Point(27116010)', 'Point(27117510)', 'Point(27118020)', 'Point(27120510)', 'Point(27123010)', 'Point(27125030)', 'Point(27125510)', 'Point(27143510)', 'Point(27146010)', 'Point(27201030)', 'Point(27201080)', 'Point(27201090)', 'Point(27201340)', 'Point(27201600)', 'Point(27202060)', 'Point(27204030)', 'Point(27205080)', 'Point(27206030)', 'Point(27207020)', 'Point(27207030)', 'Point(27207510)', 'Point(27208010)', 'Point(27209510)', 'Point(27210520)', 'Point(27211010)', 'Point(27212010)', 'Point(27213050)', 'Point(27213510)', 'Point(27214020)', 'Point(27216010)', 'Point(27216520)', 'Point(27217510)', 'Point(27218010)', 'Point(27219040)', 'Point(27221010)', 'Point(27225010)', 'Point(27225510)', 'Point(27226030)', 'Point(27227030)', 'Point(27227040)', 'Point(27301010)', 'Point(27321010)', 'Point(28102040)', 'Point(28106010)', 'Point(28107020)', 'Point(28108020)', 'Point(28108510)', 'Point(28109520)', 'Point(28111510)', 'Point(28201020)', 'Point(28201040)', 'Point(28201050)', 'Point(28201060)', 'Point(28201070)', 'Point(28201520)', 'Point(28201530)', 'Point(28202020)', 'Point(28202520)', 'Point(28202540)', 'Point(28203020)', 'Point(28203060)', 'Point(28203510)', 'Point(28204570)', 'Point(28205010)', 'Point(28206090)', 'Point(28206510)', 'Point(28207030)', 'Point(28208010)', 'Point(28208510)', 'Point(28210010)', 'Point(28210030)', 'Point(28210180)', 'Point(28210520)', 'Point(28211010)', 'Point(28212010)', 'Point(28213010)', 'Point(28214010)', 'Point(28214510)', 'Point(28216010)', 'Point(28216520)', 'Point(28217010)', 'Point(28217520)', 'Point(28218510)', 'Point(28219010)', 'Point(28381010)', 'Point(28382010)', 'Point(28464010)', 'Point(29201020)', 'Point(29202010)', 'Point(29204010)', 'Point(29206010)', 'Point(29208010)', 'Point(29209010)', 'Point(29363010)', 'Point(29425010)', 'Point(30201020)', 'Point(30201080)', 'Point(30201110)', 'Point(30201130)', 'Point(30201270)', 'Point(30202140)', 'Point(30203010)', 'Point(30322010)', 'Point(31201040)', 'Point(31203020)', 'Point(32202040)', 'Point(32204040)', 'Point(33201040)', 'Point(33201060)', 'Point(33201120)', 'Point(33201130)', 'Point(33201160)', 'Point(33201190)', 'Point(33201210)', 'Point(33202060)', 'Point(33202090)', 'Point(33202110)', 'Point(33202140)', 'Point(33202170)', 'Point(33202180)', 'Point(33202400)', 'Point(33202420)', 'Point(33202530)', 'Point(33203020)', 'Point(33204040)', 'Point(33205020)', 'Point(33208010)', 'Point(33209010)', 'Point(33210010)', 'Point(33211060)', 'Point(33423010)', 'Point(33423510)', 'Point(33503010)', 'Point(33681010)', 'Point(34102020)', 'Point(34104510)', 'Point(34105010)', 'Point(34105020)', 'Point(34105510)', 'Point(34201010)', 'Point(34201020)', 'Point(34201250)', 'Point(34201260)', 'Point(34201510)', 'Point(34201520)', 'Point(34202010)', 'Point(34202040)', 'Point(34203010)', 'Point(34204520)', 'Point(34207040)', 'Point(34207060)', 'Point(34207090)', 'Point(34207310)', 'Point(34207320)', 'Point(34207510)', 'Point(34209020)', 'Point(34211200)', 'Point(34212030)', 'Point(34369010)', 'Point(35201020)', 'Point(35201030)', 'Point(35201040)', 'Point(35201250)', 'Point(35202020)', 'Point(35202360)', 'Point(35203010)', 'Point(35204010)', 'Point(35205010)', 'Point(35206010)', 'Point(35207090)', 'Point(35208030)', 'Point(35209010)', 'Point(35211010)', 'Point(35213010)', 'Point(35214020)', 'Point(35321010)', 'Point(36201080)', 'Point(36202010)', 'Point(36205010)', 'Point(36342010)', 'Point(36361010)', 'Point(36363010)', 'Point(36381010)', 'Point(36402010)', 'Point(36461010)', 'Point(36483010)', 'Point(37201010)', 'Point(37201080)', 'Point(37201090)', 'Point(37201100)', 'Point(37201550)', 'Point(37202010)', 'Point(37203010)', 'Point(37204010)', 'Point(37205010)', 'Point(37206010)', 'Point(37322010)', 'Point(37386010)', 'Point(38201020)', 'Point(38201030)', 'Point(38201080)', 'Point(38201090)', 'Point(38201530)', 'Point(38202100)', 'Point(38204010)', 'Point(38205010)', 'Point(38205060)', 'Point(38206050)', 'Point(38208030)', 'Point(38209050)', 'Point(38212040)', 'Point(38380010)', 'Point(38401010)', 'Point(38421010)', 'Point(39201350)', 'Point(39203010)', 'Point(39206020)', 'Point(39210010)', 'Point(39212010)', 'Point(39381030)', 'Point(39405950)', 'Point(40101020)', 'Point(40101510)', 'Point(40103010)', 'Point(40103120)', 'Point(40103130)', 'Point(40105010)', 'Point(40106010)', 'Point(40107020)', 'Point(40107040)', 'Point(40108510)', 'Point(40109010)', 'Point(40109030)', 'Point(40135060)', 'Point(40135530)', 'Point(40204010)', 'Point(40206010)', 'Point(40214010)', 'Point(40621010)', 'Point(42209010)', 'Point(44201080)', 'Point(44201350)', 'Point(44202020)', 'Point(44203070)', 'Point(44213010)', 'Point(44341030)']

In [8]:
transaction_file = "PM24HeavyPollutionRecordingSensors.csv"

with open(transaction_file, "w", encoding="utf-8") as f:

    for t in transactions:

        if len(t) > 0:
            f.write(",".join(t) + "\n")

print("保存しました:", transaction_file)

保存しました: PM24HeavyPollutionRecordingSensors.csv

In [9]:
from google.colab import files
files.download(transaction_file)

In [10]:
non_empty_transactions = [
    transaction
    for transaction in transactions
    if len(transaction) > 0
]

print("全Transaction数:", len(transactions))
print("空でないTransaction数:", len(non_empty_transactions))
print("空Transaction数:", len(transactions) - len(non_empty_transactions))

transaction_lengths = [
    len(transaction)
    for transaction in non_empty_transactions
]

print("最小センサー数:", min(transaction_lengths))
print("平均センサー数:", sum(transaction_lengths) / len(transaction_lengths))
print("最大センサー数:", max(transaction_lengths))

全Transaction数: 118
空でないTransaction数: 118
空Transaction数: 0
最小センサー数: 5
平均センサー数: 133.1949152542373
最大センサー数: 625

In [3]:
from PAMI.frequentPattern.basic import FPGrowth as alg

transaction_file = "PM24HeavyPollutionRecordingSensors.csv"

# 118件の80%以上、約95件以上に出現するパターン
min_sup = 0.8

fp = alg.FPGrowth(
    transaction_file,
    min_sup,
    ","
)

fp.mine()

patterns = fp.getPatternsAsDataFrame()

print("===== Result =====")
print("minSup:", min_sup)
print("Minimum support count:", int(118 * min_sup))
print("Number of patterns:", len(patterns))
print("Runtime:", fp.getRuntime(), "seconds")
print("Memory RSS:", fp.getMemoryRSS())

display(patterns.head(20))

Frequent patterns were generated successfully using frequentPatternGrowth algorithm
===== Result =====
minSup: 0.8
Minimum support count: 94
Number of patterns: 0
Runtime: 0.00653386116027832 seconds
Memory RSS: 176365568

Empty DataFrame
Columns: [Patterns, Support]
Index: []

In [4]:
from collections import Counter

transaction_file = "PM24HeavyPollutionRecordingSensors.csv"

item_counts = Counter()
transaction_count = 0

with open(transaction_file, "r", encoding="utf-8") as f:
    for line in f:
        items = [
            item.strip()
            for item in line.strip().split(",")
            if item.strip()
        ]

        transaction_count += 1
        item_counts.update(set(items))

print("Transaction数:", transaction_count)
print("異なるセンサー数:", len(item_counts))

print("\n出現回数が多いセンサー上位20件")

for sensor, count in item_counts.most_common(20):
    rate = count / transaction_count

    print(
        sensor,
        "出現回数:", count,
        "出現割合:", f"{rate:.3f}"
    )

Transaction数: 118
異なるセンサー数: 962

出現回数が多いセンサー上位20件
Point(16201400) 出現回数: 58 出現割合: 0.492
Point(40105010) 出現回数: 53 出現割合: 0.449
Point(13201040) 出現回数: 42 出現割合: 0.356
Point(40101020) 出現回数: 42 出現割合: 0.356
Point(13201510) 出現回数: 42 出現割合: 0.356
Point(13201020) 出現回数: 41 出現割合: 0.347
Point(07204210) 出現回数: 40 出現割合: 0.339
Point(09205010) 出現回数: 39 出現割合: 0.331
Point(14209050) 出現回数: 38 出現割合: 0.322
Point(13103510) 出現回数: 38 出現割合: 0.322
Point(33423010) 出現回数: 37 出現割合: 0.314
Point(08203010) 出現回数: 37 出現割合: 0.314
Point(10203010) 出現回数: 37 出現割合: 0.314
Point(30322010) 出現回数: 36 出現割合: 0.305
Point(34207060) 出現回数: 36 出現割合: 0.305
Point(13101010) 出現回数: 36 出現割合: 0.305
Point(45203520) 出現回数: 36 出現割合: 0.305
Point(14401010) 出現回数: 35 出現割合: 0.297
Point(28202580) 出現回数: 35 出現割合: 0.297
Point(33201190) 出現回数: 35 出現割合: 0.297

In [5]:
max_sensor, max_count = item_counts.most_common(1)[0]
max_rate = max_count / transaction_count

print("最も多く出現したセンサー:", max_sensor)
print("最大出現回数:", max_count)
print("最大出現割合:", max_rate)

最も多く出現したセンサー: Point(16201400)
最大出現回数: 58
最大出現割合: 0.4915254237288136

In [6]:
min_sup = max_rate * 0.9

print("次に使用するminSup:", min_sup)
print(
    "最小支持度数:",
    int(transaction_count * min_sup)
)

次に使用するminSup: 0.4423728813559322
最小支持度数: 52

In [7]:
from PAMI.frequentPattern.basic import FPGrowth as alg

fp = alg.FPGrowth(
    transaction_file,
    min_sup,
    ","
)

fp.mine()

patterns = fp.getPatternsAsDataFrame()

print("===== Result =====")
print("minSup:", min_sup)
print("Number of patterns:", len(patterns))
print("Runtime:", fp.getRuntime(), "seconds")
print("Memory RSS:", fp.getMemoryRSS())

display(patterns.head(20))

Frequent patterns were generated successfully using frequentPatternGrowth algorithm
===== Result =====
minSup: 0.4423728813559322
Number of patterns: 2
Runtime: 0.007862567901611328 seconds
Memory RSS: 177074176

          Patterns  Support
0  Point(40105010)       53
1  Point(16201400)       58

In [8]:
from PAMI.frequentPattern.basic import FPGrowth as alg

transaction_file = "PM24HeavyPollutionRecordingSensors.csv"
min_sup = 0.35

fp = alg.FPGrowth(
    transaction_file,
    min_sup,
    ","
)

fp.mine()

patterns = fp.getPatternsAsDataFrame()

print("===== Result =====")
print("minSup:", min_sup)
print("Minimum support count:", int(118 * min_sup))
print("Number of patterns:", len(patterns))
print("Runtime:", fp.getRuntime(), "seconds")
print("Memory RSS:", fp.getMemoryRSS())

display(patterns.head(30))

Frequent patterns were generated successfully using frequentPatternGrowth algorithm
===== Result =====
minSup: 0.35
Minimum support count: 41
Number of patterns: 5
Runtime: 0.04754900932312012 seconds
Memory RSS: 177713152

          Patterns  Support
0  Point(13201040)       42
1  Point(40101020)       42
2  Point(13201510)       42
3  Point(40105010)       53
4  Point(16201400)       58

In [9]:
def pattern_length(pattern):
    if isinstance(pattern, (list, tuple, set)):
        return len(pattern)

    text = str(pattern).strip()

    # PAMIではタブ区切りで複数項目が入ることがある
    if "\t" in text:
        return len([x for x in text.split("\t") if x.strip()])

    # カンマ区切りの場合にも対応
    if "," in text:
        return len([x for x in text.split(",") if x.strip()])

    return 1 if text else 0


patterns["Length"] = patterns["Patterns"].apply(pattern_length)

print("最長パターンの長さ:", patterns["Length"].max())

display(
    patterns.sort_values(
        by=["Length", "Support"],
        ascending=[False, False]
    ).head(20)
)

最長パターンの長さ: 1

          Patterns  Support  Length
4  Point(16201400)       58       1
3  Point(40105010)       53       1
0  Point(13201040)       42       1
1  Point(40101020)       42       1
2  Point(13201510)       42       1

In [10]:
from PAMI.frequentPattern.basic import FPGrowth as alg

transaction_file = "PM24HeavyPollutionRecordingSensors.csv"
min_sup = 0.30

fp = alg.FPGrowth(
    transaction_file,
    min_sup,
    ","
)

fp.mine()

patterns = fp.getPatternsAsDataFrame()

print("===== Result =====")
print("minSup:", min_sup)
print("Minimum support count:", int(118 * min_sup))
print("Number of patterns:", len(patterns))
print("Runtime:", fp.getRuntime(), "seconds")
print("Memory RSS:", fp.getMemoryRSS())

display(patterns.head(30))

Frequent patterns were generated successfully using frequentPatternGrowth algorithm
===== Result =====
minSup: 0.3
Minimum support count: 35
Number of patterns: 21
Runtime: 0.010602951049804688 seconds
Memory RSS: 178466816

                                           Patterns  Support
0                                   Point(30322010)       36
1                                   Point(34207060)       36
2                                   Point(13101010)       36
3                                   Point(45203520)       36
4                                   Point(08203010)       37
5                                   Point(33423010)       37
6                                   Point(10203010)       37
7                                   Point(14209050)       38
8                                   Point(13103510)       38
9                                   Point(09205010)       39
10                                  Point(07204210)       40
11                                  Point(13201020)       41
12                  Point(13201020),Point(13201040)       39
13                  Point(13201020),Point(13201510)       39
14  Point(13201020),Point(13201510),Point(13201040)       37
15                                  Point(13201040)       42
16                                  Point(40101020)       42
17                                  Point(13201510)       42
18                  Point(13201510),Point(13201040)       39
19                                  Point(40105010)       53
20                                  Point(16201400)       58

In [11]:
def pattern_length(pattern):
    if isinstance(pattern, (list, tuple, set)):
        return len(pattern)

    text = str(pattern).strip()

    if "\t" in text:
        return len([x for x in text.split("\t") if x.strip()])

    if "," in text:
        return len([x for x in text.split(",") if x.strip()])

    return 1 if text else 0


patterns["Length"] = patterns["Patterns"].apply(pattern_length)

print("最長パターンの長さ:", patterns["Length"].max())

display(
    patterns.sort_values(
        by=["Length", "Support"],
        ascending=[False, False]
    ).head(20)
)

最長パターンの長さ: 3

                                           Patterns  Support  Length
14  Point(13201020),Point(13201510),Point(13201040)       37       3
12                  Point(13201020),Point(13201040)       39       2
13                  Point(13201020),Point(13201510)       39       2
18                  Point(13201510),Point(13201040)       39       2
20                                  Point(16201400)       58       1
19                                  Point(40105010)       53       1
15                                  Point(13201040)       42       1
16                                  Point(40101020)       42       1
17                                  Point(13201510)       42       1
11                                  Point(13201020)       41       1
10                                  Point(07204210)       40       1
9                                   Point(09205010)       39       1
7                                   Point(14209050)       38       1
8                                   Point(13103510)       38       1
4                                   Point(08203010)       37       1
5                                   Point(33423010)       37       1
6                                   Point(10203010)       37       1
0                                   Point(30322010)       36       1
1                                   Point(34207060)       36       1
2                                   Point(13101010)       36       1

In [12]:
pattern_file = "frequentPatterns.txt"

fp.save(pattern_file)

print("Saved:", pattern_file)

Saved: frequentPatterns.txt

In [13]:
with open(pattern_file, "r", encoding="utf-8") as f:
    for i, line in enumerate(f):
        print(line.strip())
        if i >= 19:
            break

Point(30322010):36
Point(34207060):36
Point(13101010):36
Point(45203520):36
Point(08203010):37
Point(33423010):37
Point(10203010):37
Point(14209050):38
Point(13103510):38
Point(09205010):39
Point(07204210):40
Point(13201020):41
Point(13201020)	Point(13201040):39
Point(13201020)	Point(13201510):39
Point(13201020)	Point(13201510)	Point(13201040):37
Point(13201040):42
Point(40101020):42
Point(13201510):42
Point(13201510)	Point(13201040):39
Point(40105010):53

In [14]:
longest_row = patterns.sort_values(
    by=["Length", "Support"],
    ascending=[False, False]
).iloc[0]

longest_pattern_text = longest_row["Patterns"]
longest_support = longest_row["Support"]

longest_sensors = [
    item.strip()
    for item in longest_pattern_text.split(",")
    if item.strip()
]

print("Longest pattern:", longest_sensors)
print("Pattern length:", len(longest_sensors))
print("Support:", longest_support)

Longest pattern: ['Point(13201020)', 'Point(13201510)', 'Point(13201040)']
Pattern length: 3
Support: 37

In [15]:
import re

longest_sensor_ids = []

for sensor in longest_sensors:
    match = re.search(r"Point\((\d+)\)", sensor)

    if match:
        longest_sensor_ids.append(match.group(1))

print("Sensor IDs:", longest_sensor_ids)

Sensor IDs: ['13201020', '13201510', '13201040']

In [17]:
import os

for file in os.listdir():
    print(file)

.config
PM24HeavyPollutionRecordingSensors.csv
airPollutionDataFrame.csv
frequentPatterns.txt
sample_data

In [18]:
from google.colab import files

uploaded = files.upload()

Saving stationInfo.csv to stationInfo.csv

In [19]:
import os
print(os.listdir())

['.config', 'PM24HeavyPollutionRecordingSensors.csv', 'airPollutionDataFrame.csv', 'stationInfo.csv', 'frequentPatterns.txt', 'sample_data']

In [21]:
import pandas as pd

location_df = pd.read_csv(
    "stationInfo.csv",
    encoding="utf-8"
)

print(location_df.columns.tolist())
display(location_df.head())

['rowNumber', 'stationId', 'Location', 'Address']

   rowNumber  stationId                              Location          Address
0          1    1101010  Point(141.3532777 43.06225480000001)       札幌市中央区北１西２
1          2    1101020         Point(141.3252375 43.0396273)     札幌市中央区南２３西１３
2          3    1101520  Point(141.3532777 43.06225480000001)       札幌市中央区北１西２
3          4    1101540         Point(141.3445286 43.0409769)  札幌市中央区南１４条西１０丁目
4          5    1102010         Point(141.3711567 43.1453261)       札幌市北区篠路４－９

In [22]:
import re
import pandas as pd

# stationIdを8桁の文字列にそろえる
location_df["stationId"] = (
    location_df["stationId"]
    .astype(str)
    .str.replace(".0", "", regex=False)
    .str.zfill(8)
)

def parse_location(location):
    match = re.search(
        r"Point\(\s*([-\d.]+)\s+([-\d.]+)\s*\)",
        str(location),
        re.IGNORECASE
    )

    if match is None:
        return pd.Series([None, None])

    longitude = float(match.group(1))
    latitude = float(match.group(2))

    return pd.Series([longitude, latitude])

location_df[["Longitude", "Latitude"]] = location_df["Location"].apply(
    parse_location
)

display(location_df.head())

,rowNumber,stationId,Location,Address,Longitude,Latitude
0,1,01101010,Point(141.3532777 43.06225480000001),札幌市中央区北１西２,141.353278,43.062255
1,2,01101020,Point(141.3252375 43.0396273),札幌市中央区南２３西１３,141.325237,43.039627
2,3,01101520,Point(141.3532777 43.06225480000001),札幌市中央区北１西２,141.353278,43.062255
3,4,01101540,Point(141.3445286 43.0409769),札幌市中央区南１４条西１０丁目,141.344529,43.040977
4,5,01102010,Point(141.3711567 43.1453261),札幌市北区篠路４－９,141.371157,43.145326

In [23]:
longest_sensor_ids = [
    "13201020",
    "13201510",
    "13201040"
]

target_locations = location_df[
    location_df["stationId"].isin(longest_sensor_ids)
].copy()

print("抽出件数:", len(target_locations))
display(
    target_locations[
        ["stationId", "Address", "Latitude", "Longitude"]
    ]
)

抽出件数: 3

    stationId        Address   Latitude   Longitude
557  13201020   八王子市片倉町５５３番地  35.644981  139.339833
558  13201040  八王子市館町１０９７－６６  35.628343  139.287173
560  13201510       八王子市八木町８  35.661852  139.321068

In [24]:
import plotly.express as px

fig = px.scatter_map(
    target_locations,
    lat="Latitude",
    lon="Longitude",
    hover_name="stationId",
    hover_data={
        "Address": True,
        "Latitude": True,
        "Longitude": True
    },
    zoom=10,
    height=600,
    title=(
        "Longest Frequent Pattern of Heavy PM2.5 Sensors "
        "(Length = 3, Support = 37)"
    )
)

fig.update_traces(
    marker={"size": 18}
)

fig.update_layout(
    map_style="open-street-map",
    margin={"r": 0, "t": 60, "l": 0, "b": 0}
)

fig.show()